version: '3.8'
services:
  confluence:
    image: cptactionhank/atlassian-confluence
    restart: unless-stopped
    ports:
      - 8090:8090
    networks:
      - confluence-mysql_custom-network
    container_name: confluence

networks:
  confluence-mysql_custom-network:
   external: true
