version: "3.8"
services:
  confluence-mysql:
    container_name: confluence-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - custom-network
    volumes:
      - ./volume/db/:/var/lib/mysql/
      - ./volume/conf/my.cnf:/etc/my.cnf

networks:
  custom-network:
