version: "3.8"
services:
  nexus:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./volume/jenkins_home:/var/jenkins_home
