version: "3.8"
services:
  jira-mysql:
    container_name: jira-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volume/mysql/db/:/var/lib/mysql/
      - ./volume/mysql/conf/my.cnf:/etc/my.cnf

  jira:
    container_name: jira
    image: registry.cn-beijing.aliyuncs.com/huyuan/atlassian-jira-software:latest
    user: root
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
    ports:
      - 8001:8080
    volumes:
      - ./volume/jira/jira/:/var/atlassian/jira
