version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - network
    volumes:
      - ./volume/db/:/var/lib/mysql/
      - ./volume/conf/my.cnf:/etc/my.cnf

networks:
  network:
